### ISSUE TITLE
Support of older object types and object variants.

### ISSUE THREAD

**Issue by FSharpCSharp** [jhoek/UncommonSense.CBreeze#123]
Before I start with my suggestions for improvement, I would like to praise the creation of such an extensive tool for editing C/AL text files. It's nice to see you put so much energy into this project and how big it is! Respect for that and keep up the good work!

Now to my suggestions for improvement. It would be great if you could also support the old object types in this project. I mean mainly Forms and Dataports. It would be really great here if you had the right tools for this. Furthermore, it would be great if you could support the old report structure with the sections and the RequestForm. This would allow you to take full advantage of this SDK. Maybe I could even contribute something to these points, because I already had a lot to do with it. I just don't want to promise too much, but maybe.

**Comment by jhoek** [comment]
@FSharpCSharp Thank you very much for your kind words! Mostly due to my own complete lack of marketing skills ;-), the project hasn't really had the exposure it probably deserves, so it's nice to see that smart people apparently are able to find it by themselves! :-)

Regarding the older versions - I'm using C/Breeze quite intensively in my job working on a NAV 2017 CU 2.1 add-on. With the focus on that version, and limited spare time, supporting older NAV versions has become a bit of a burden, TBH. 

The idea for an API like this has been on my mind for the past 10-15 years. Since then, I've spent so much time learning about the techniques and project management skills involved that the fruit of my labour, which is now nearing completion, is almost obsolete as MS is moving towards AL. That is another reason why, in all honesty, I don't see myself adding backward compatibility with older NAV versions (but I would gladly accept pull requests, of course!).

Instead, I think I'd like to build something like C/Breeze, but for AL, Microsoft's new programming language for Dynamics NAV (or whatever the product is called these days). And this time, I'll try to finish it before Microsoft introduces something else entirely. ;-)

I'm sorry if the above wasn't quite the answer you were hoping for. If you do decide to add support for older NAV version yourself, I can certainly offer you my support (and sincere appreciation)! Looking forward to hearing from you!

**Comment by FSharpCSharp** [comment]
Thank you very much for the quick and detailed answer! I think it's great enough that there is a community project to work with these files. I had already asked for something like this in the Microsoft/AL project, because Microsoft apparently uses such an SDK for the new Mergetool itself. Unfortunately my request was refused to publish it under Open Source because there are dependencies on third party products that should not be published. That's why this SDK comes in handy.

To your idea for an SDK for the new AL language. I immediately agree with you that something like this is needed. To my knowledge, this was already asked for in the Microsoft/AL project. Many people already wish for something like this as a community project. From my point of view it would be great if you could put this project under an open source license, so that everyone from the community can participate. There are apparently already many, which look for exactly such a thing (if one can trust the inquiries in the Microsoft/AL project).

I'll worry about the types of objects that are still missing. Perhaps these can be added without too much effort.

Oh, another question about the license you asked the project under. Why did you explicitly choose the GPL? Wouldn't an Apache 2.0 or MIT license have worked? Microsoft itself only licenses everything under MIT, and that's actually cool. If you don't want to maintain this product here anyway, then such a license would be a lot more practical for everyday use. Especially in the business environment the GPL license has not really proven itself.

**Comment by jhoek** [comment]
Yeah, I guess you're right. Judging from my past experiences, though, I didn't think that many people understood the power of having an API for querying and manipulating one's NAV application source code. I usually takes quite some time to explain the idea behind C/Breeze, even to experienced C/AL developers. 

Imagine all the C/AL parsers that people have built over the past decades to power their individual utilities. Even the Navision Developer's Toolkit had it's own parser, I think, independent from the one built into fin(sql).exe. How much more and cleverer tooling would we have had with a proper API, eh? 

Regarding the license - I'm not a big expert in this field. I just picked the license that seemed most appropriate, i.e. struck had the right balance between openness and still protecting my intellectual investment in this project. I'm certainly willing to listen to anyone who wishes to convince me that another license would be a better choice! :-)

**Comment by jhoek** [comment]
@FSharpCSharp BTW, could you point me at some of the AL repo issues about this subject? Maybe I'm using the wrong search terms, but I'm not finding any?

**Comment by FSharpCSharp** [comment]
I'll see about the missing object types, that we can integrate them into your existing program. There will certainly be a solution, then there is a complete open source object model for the old C/AL, which is easy to use for the user.

To return to the topic of licensing. I'm not an expert here either, but I've been observing the topic for a while now, and I can tell you from experience that the GPL causes more problems than advantages in the business environment. One reason for this is that this license is very restrictive, and you are already violating it without wanting to. This has often happened with the Linux kernel in the past, because many were unaware that this license requires that you give up all rights. For this reason, for example, Microsoft has opted for the MIT license. The advantage over the GPL license is that everyone understands the license. The main difference to the GPL is that you can safely integrate the third party product into an existing application without publishing your own source code. This is the crux of the GPL license. You are forced to publish your code under this license, even if you only link to the library. And many have already burned their fingers in this. Therefore I suggest that you put your product under a different license to avoid these problems. It is important that you choose a license that a normal user understands and that does not contain such a strong copyleft as the standard GPL license. Otherwise no one in the daily business will use this great library. And in my opinion that would be a real shame if this library were to run dry, and no one would use it, since you have invested so much energy and passion.

**Comment by jhoek** [comment]
Yes, that seems to make sense, and you are certainly very right about the time and energy invested! ;-) 

From what I had understood before (did I mention I'm not an expert? ;-)), it is possible to have multiple license models for multiple "target audiences". I thought GPL could help prevent more commercially savvy people than I am from putting a thin wrapper around the library and selling it at a profit. For those people, a different license model could be agreed upon for each individual case. 

All others, that just used the library to build their own scripts etc., would then be covered by the GPL license?

**Comment by FSharpCSharp** [comment]
@jhoek Propose this project to the ".NET-Foundation".

Yesterday I had to deal with some very meaningful projects of the".NET-Foundation", and I heard from everyone who reported their project there that it has made enormous progress with the projects. Once again your great project came to my mind, and I just wanted to suggest that you register your project there. You would have some advantages here, and would also receive support. It would also be supported by Microsoft. You would even receive financial support for the development. That sounds excellent. I can personally imagine very well that your project would be ideal for this. An up-and-coming library that makes life easier for everyone. If the project is a member of".NET-Foundation", it will be easier to find. I'll post the link here. You can read through it and take part in it if necessary! I think it would be an incredible enrichment for the .NET Foundation.

[.NET Foundation - Get Involved](https://www.dotnetfoundation.org/get-involved)

**Comment by jhoek** [comment]
@FSharpCSharp Hmmm... That sounds interesting. I'll try and take a closer look next Wednesday. Thanks for making me aware of this possibility!

**Comment by jhoek** [comment]
Regarding the license - as you could tell from my earlier response, I should probably spend some more time on the subject. Also planned for Wednesday...

**Comment by jhoek** [comment]
(Haven't forgotten about this, but spent my Wednesday working on a bug that I found earlier this week...)

**Comment by jhoek** [comment]
@FSharpCSharp 
- Changed the license to MIT as per your suggestion - thanks!;
- Will consider making my AL project a member of the .NET Foundation, but not C/Breeze;
- The older object types I will leave as an exercise for the user ;-), so I think this issue no longer represents any pending work for me and should therefore be closed - I hope you'll agree. Looking forward to your pull request! :-)

**Comment by FSharpCSharp** [comment]
@jhoek 
Thank you for changing your license! I really appreciate you taking on this complex subject. Believe me, I know from my own experience how unpleasant it is to deal with it.

Regarding the older object types. I'm definitely on the subject. But you know how it is when you have a lot on your mind professionally, the priorities are usually somewhere else. But it's definitely my turn, and I'll take care of it. Then we really have a great API that opens up so many new possibilities.

Thanks again for your great work!

**Comment by FSharpCSharp** [comment]
@jhoek 
I have another question, which I noticed when implementing the forms and dataports. Unfortunately there is an absurdity with the MenuButton how the MenuItems are handled. In the text file they look like this:

```
Menu=MENUITEMS
                                                 {
                                                   { ID=75;
                                                     PushAction=LookupTable;
                                                     ShortCutKey=F5;
                                                     CaptionML=[ENU=List] }
                                                   { ID=80;
                                                     PushAction=RunObject;
                                                     ShortCutKey=Strg+F5;
                                                     CaptionML=[ENU=Ledger E&ntries];
                                                     RunObject=Form 25;
                                                     RunFormLinkType=OnUpdate;
                                                     RunFormView=SORTING(Customer No.);
                                                     RunFormLink=Customer No.=FIELD(No.) }
                                                   { ID=134;
                                                     CaptionML=[ENU=Sales &History] }
```

As you can see, all of them are actually just properties. There are no real elements, as with the page controls. The ID is also handled very strangely.  Do you have any idea how best to do this? Have you ever had a case like this anywhere before?

**Comment by jhoek** [comment]
@FSharpCSharp The menu items appear to be similar to (coincidence?) the ActionList property of a page, in that they are "just a normal property", but the structure of the property value is rather complicated. Is that what you mean?

**Comment by FSharpCSharp** [comment]
@jhoek 
No, my point is that everything is properties. For all other elements, there are still the mandatory properties in the current line, and without propertname=value. Hence my question, how to map in the model? Belongs to the MenuItemProperty class according to your previous logic.

**Comment by jhoek** [comment]
@FSharpCSharp Ah, now I understand (I think...). Since ID is by definition unique, I would probably define a class with only an ID-property (and an optional Name if the menu-items have one - I don't remember exactly). All the other properties would go in a separate class called MenuItemProperties. Each menu-item would then have a Properties property containing an instance of this class, so that you could write `MyMenuItem.Properties.ShortCutKey = '...SomeShortcut...'`. 

Not sure if menu-items that contain other menu items should have a separate class - after all, they probably don't run an object themselves, which makes their behaviour different from a typical leaf-level menu-item?

**Comment by FSharpCSharp** [comment]
@jhoek 
That's exactly what I wanted to know. I'm beginning to realize why Microsoft has modernized this old text format a bit with the new AL world. I sometimes find it made very inconsistent. It's obvious that a lot of different people have been working on it.

**Comment by FSharpCSharp** [comment]
Absolutely. I didn't understand that from the beginning, why all this is done with such stupid indents, and what's more, there aren't even escape characters for protected characters everywhere. The best example is the TableView. Here you can even insert fields with brackets, and these are not even written in escape characters. Only with the introduction of the new format (you can use PowerShell to output all objects in a slightly more modern format which is required for automatic conversion to the AL world) were these characters escaped at all. Some other details have also been improved. The fact that there is such a thing already speaks for the fact that Microsoft itself needs information here, which they do not have or did not have in the files so far. It really is a testament to poverty, as has been added more and more in this format, instead of bringing the whole thing into an easily parsable ENBF. Then parsing would really not be a problem for us.
