### ISSUE TITLE
Error when parsing a test object

### ISSUE THREAD

**Issue by FSharpCSharp** [jhoek/UncommonSense.CBreeze#126]
I have now played a little with the library, and tried some test cases. This also includes the recognition of objects that contain special characters and brackets in the name and in various variables.

But I had some problems testing the following file. This file is a valid object file that you can read into Dynamics NAV exactly as it is. The file looks funny, but it works. I didn't make these up. It is only used by our development system to test various special character tests on SQL Server and during compilation.

Therefore, the file should also be readable, even if these cases may hardly occur in reality, but they can occur.

[TestTable.txt](https://github.com/jhoek/UncommonSense.CBreeze/files/1995180/TestTable.txt)

**Comment by jhoek** [comment]
Haha! That probably breaks my parser (entirely based on reverse engineering) in a million different ways! As such, a very useful test! I'll look into this ASAP.

**Comment by jhoek** [comment]
@FSharpCSharp Getting (object) dates and times to match without knowing the culture used to export them cannot be done with 100% accuracy. For now, when testing with your sample file, I'll reformat the date/time to match my local settings. Makes sense?

**Comment by jhoek** [comment]
@FSharpCSharp Do you know if it's only curly brackets that cause the square brackets around property values containing them? Or are there other characters that trigger this behaviour?

**Comment by FSharpCSharp** [comment]
@jhoek 
So what I know about all the bracketed stories so far is this:

There are apparently escape sequences to allow the parentheses and special characters. However, the square brackets are always the object if it is a sign that has an ambiguous meaning. For field names, for example, it is also the semicolon. This makes sense because it can also serve as a separator between the individual values.

There is a similar behavior with multi-language texts, if the text contains an is-identical character, or quotation marks. But beware! What I know so far is that this kind of escaping can occur almost everywhere. This means that it would be best to provide for this case everywhere. But you can play through such a case relatively well in NAV by building a page around this table or using it elsewhere. A similar behaviour must take place here.

**Comment by FSharpCSharp** [comment]
@jhoek 
I built you some more examples of the special characters today. I attached this file to you. 

[special_char_tests.txt](https://github.com/jhoek/UncommonSense.CBreeze/files/2001116/special_char_tests.txt)

**Comment by FSharpCSharp** [comment]
@jhoek 
I found something else for you to see the date and time. The detection is indeed dependent on many parameters. But I would try the [TryParse](https://docs.microsoft.com/de-de/dotnet/api/system.datetime.tryparse?view=netframework-4.7.1) function of DateTime if I were you. There is also an overload for this method that uses the IFormatProvider interface. Perhaps it would be an option to try to determine these options using these parameters, and additionally offer the user the possibility to provide an IFormatProvider. It goes even further: This sometimes affects not only the date formats but also the entire character set of the object. So far you are using the function "Encoding.GetEncoding(850)". This will work for most Western European countries, but not for all languages. Here it would be good if you could record this information from the user and get all the information at runtime using the IFormatProvider.
