### ISSUE TITLE
Gets rid of compiler parameters?

### ISSUE THREAD

**Issue by FSharpCSharp** [jhoek/UncommonSense.CBreeze#133]
Hello,

my colleagues have now also discovered your framework, and are excited about the possibilities it offers. It's always great to see how much heart and soul goes into a project.

My colleagues have only noticed that the mapping of NAV versions depends on compilation parameters. Unfortunately, this is not really good, because it actually breaks the object orientation a bit. My colleagues are therefore wondering whether we could not get away with this and solve the problem in a different way with different versions.

I had already asked myself such a question, because I work on forms and dataports from time to time, and these are only available in older versions. Here, too, I would have had to work with parameters so far.

I would therefore like to ask you whether you are working on better solutions or have a few ideas on how to solve the issue in a different way. Doesn't inheritance help in such cases? Then you could separate all this much cleaner, I think.

**Comment by jhoek** [comment]
@FSharpCSharp Exactly what I'm thinking about right now, because of the following: the current setup would also imply that I publish a separate PowerShell Gallery for each (NAV) version. Any suggestions on how to solve this are very welcome. I do want e.g. my property classes to be type-safe and tailored to a NAV version, i.e. a table property that was introduced in NAV2017 should only exist in the TableProperties class for versions 2017 and 2018.

Also, I cannot make changes that are too drastic, because I'm already using the API as it currently is.

**Comment by FSharpCSharp** [comment]
Well, personally, I think that you could solve many of those problems with heredity. I think that the Windows Forms Framework is very similar to yours, because there are properties here as well, and various controls, which all use inheritance. You can have a look at the source code of [Mono](https://github.com/mono/mono/tree/master/mcs/class/System.Windows.Forms/System.Windows.Forms), the open source implementation of.NET. I think if you did it that way, it would be the right way. In addition, almost everyone who works with .NET knows it.

**Comment by jhoek** [comment]
Assuming you are not underestimating the problem, you may have overestimated my knowledge... ;-)

Do you mean something like the following:
- an abstract base class for e.g. TableProperties;
- derived classes for each NAV version;
- a factory for instantiating TableProperties, based on the NAV version;
- a way to tell an Application instance which version it should support.

**Comment by FSharpCSharp** [comment]
For God's sake, no, I'm not better or worse here. I only saw the similarity to Windows Forms, because here you can easily convert an existing application from e.g. .NET 2.0 to.NET 4.5, and although there are changes with Properties, this is no problem. I find the following concepts from Windows Forms quite ingenious, and you should use them in my eyes.

In System Windows Forms, the properties have an attibut so that the properties that are important can be determined automatically. See the following class as an [example](https://github.com/mono/mono/blob/master/mcs/class/System.Windows.Forms/System.Windows.Forms/PropertyGrid.cs).

Imagine that you would want to use your development with the above PropertyGrid to give users the ability to easily change it. This has not yet been possible under the current concept. A concept would be important for your implementation of the entire properties. The EntityFramework, for example, works exclusively with attributes. This would eliminate, for example, the internally maintained property list for each object and its components. The properties would only be recognized with the help of attributes or special classes. That would work, because you already have a property class. With the help of reflection I think you should be able to determine all properties completely automatically. This would completely eliminate the additional internal administration. You could still manage the properties in your own collection, but then it would make sense to create this list dynamically at runtime, or to work with configuration files such as XML or JSON. Then all this is not hard-coded. So that the properties can then be used directly on the object, so to speak, you could still leave the call as it is now. The only problem I see here is that properties could of course be omitted in certain versions. One would have to think about how to deal with it, because this cannot necessarily be solved by inheritance. But let's not start with the worst-case scenario.

It's very hard to go either one way or the other. Certain cases will always not work. In principle, however, this applies to all programmes. I have a hard time suggesting something to you because I don't know how far you would want to provide graphical interfaces. All this requires special concepts that cannot be developed overnight. If I were you, I would try some concepts with an object type, for example the table. You will already notice the advantages and disadvantages during the development.

**Comment by jhoek** [comment]
Yeah, I've been thinking about reorganizing the property classes. There are, however, a few things to take into consideration: the properties have a "natural" order according to NAV; I guess that could be an attribute parameter. Also, the classes derived from Properties are capable of enumerating their properties, but also have type-safe members (properties). Both changing the Value of a property and changing the type-safe members should set the property value - these two actions should be 100% equivalent.

Omitting irrelevant properties would be significantly easier using your idea, but how would you also omit the corresponding type-safe members? 

All in all, I'm worried that it might break some stuff, and also, cost a lot of time which cannot be spent creating a "C/Breeze for AL", which has my personal priority. If you can think of a light-weight and low-risk change for the properties, I'm certainly all for it! :-)

**Comment by FSharpCSharp** [comment]
That's all right. But this problem has happened to me several times in my professional life. Unfortunately, you can't plan everything 100 percent. Many errors and problems only occur after a solution has been worked out. I would also invest more time in this great project, but unfortunately I can't get around to it. It's not nice, but at the moment, when everything is changing, there are so many exciting topics that you could familiarize yourself with. But let's put it this way: take care of everything with a clear conscience and head. I totally understand your priorities. See it all in the positive side. Even though it looks like I'm just speaking wisely. The great thing about an open source project is that you learn an incredible amount and improve yourself. There are many things you can't do alone, but someone else gives you a hint. Unfortunately, from my own experience, the entire topic of Open Source is still neglected within companies. While in the private sector it has already penetrated almost everyone. I'll definitely stay on the subject, even if it's private.

**Comment by jhoek** [comment]
@FSharpCSharp I'll close the issue for now, but if you have any concrete suggestions for tackling this problem, please feel free to reopen it! Thanks again for your time & effort!
